window.LIVING_META_LIBRARY = {
    "generatedAt":  "2026-05-25T10:43:43.2365464+01:00",
    "items":  [
                  {
                      "name":  "ATTR_CM_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/ATTR_CM_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/ATTR_CM_REVIEW.v11.bak.html",
                      "copyName":  "ATTR_CM_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4860000+01:00",
                      "sizeBytes":  27518,
                      "sizeLabel":  "26.9 KB"
                  },
                  {
                      "name":  "COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyName":  "COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:16:25.6570000+01:00",
                      "sizeBytes":  817575,
                      "sizeLabel":  "798.4 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyName":  "FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:16:25.6950000+01:00",
                      "sizeBytes":  661103,
                      "sizeLabel":  "645.6 KB"
                  },
                  {
                      "name":  "GLP1_CVOT_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyName":  "GLP1_CVOT_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:16:25.7500000+01:00",
                      "sizeBytes":  1107435,
                      "sizeLabel":  "1,081.5 KB"
                  },
                  {
                      "name":  "INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyName":  "INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:07:28.6440000+01:00",
                      "sizeBytes":  430822,
                      "sizeLabel":  "420.7 KB"
                  },
                  {
                      "name":  "livingmeta -- LivingMeta_backup.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/livingmeta -- LivingMeta_backup.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/livingmeta -- LivingMeta_backup.html",
                      "copyName":  "livingmeta -- LivingMeta_backup.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:16:25.8310000+01:00",
                      "sizeBytes":  963352,
                      "sizeLabel":  "940.8 KB"
                  },
                  {
                      "name":  "livingmeta -- LivingMeta_backup2.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/livingmeta -- LivingMeta_backup2.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/livingmeta -- LivingMeta_backup2.html",
                      "copyName":  "livingmeta -- LivingMeta_backup2.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:16:25.8870000+01:00",
                      "sizeBytes":  965011,
                      "sizeLabel":  "942.4 KB"
                  },
                  {
                      "name":  "SGLT2_HF_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "Library/Backup/Finrenone Backups/",
                      "originalPath":  "Library/Backup/Finrenone Backups/SGLT2_HF_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Backup/Finrenone Backups/SGLT2_HF_REVIEW.v11.bak.html",
                      "copyName":  "SGLT2_HF_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Backup/Finrenone Backups/",
                      "lastWriteIso":  "2026-04-23T20:16:25.9470000+01:00",
                      "sizeBytes":  830685,
                      "sizeLabel":  "811.2 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "ESC ACS Living Meta",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/ESC ACS Living Meta/",
                      "originalPath":  "Library/Current/ESC ACS Living Meta/index.html",
                      "copyPath":  "Library/Current/ESC ACS Living Meta/index.html",
                      "copyName":  "index.html",
                      "folderPath":  "Library/Current/ESC ACS Living Meta/",
                      "lastWriteIso":  "2026-04-23T20:07:27.6330000+01:00",
                      "sizeBytes":  34912,
                      "sizeLabel":  "34.1 KB"
                  },
                  {
                      "name":  "r-validation-runner.html",
                      "category":  "Current",
                      "group":  "ESC ACS Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/ESC ACS Support/",
                      "originalPath":  "Library/Current/ESC ACS Support/r-validation-runner.html",
                      "copyPath":  "Library/Current/ESC ACS Support/r-validation-runner.html",
                      "copyName":  "r-validation-runner.html",
                      "folderPath":  "Library/Current/ESC ACS Support/",
                      "lastWriteIso":  "2026-01-26T10:11:35.7400000+00:00",
                      "sizeBytes":  14161,
                      "sizeLabel":  "13.8 KB"
                  },
                  {
                      "name":  "test-runner.html",
                      "category":  "Current",
                      "group":  "ESC ACS Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/ESC ACS Support/",
                      "originalPath":  "Library/Current/ESC ACS Support/test-runner.html",
                      "copyPath":  "Library/Current/ESC ACS Support/test-runner.html",
                      "copyName":  "test-runner.html",
                      "folderPath":  "Library/Current/ESC ACS Support/",
                      "lastWriteIso":  "2026-01-26T10:11:54.3070000+00:00",
                      "sizeBytes":  3759,
                      "sizeLabel":  "3.7 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "Finrenone LivingMeta Copies",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Finrenone LivingMeta Copies/",
                      "originalPath":  "Library/Current/Finrenone LivingMeta Copies/index.html",
                      "copyPath":  "Library/Current/Finrenone LivingMeta Copies/index.html",
                      "copyName":  "index.html",
                      "folderPath":  "Library/Current/Finrenone LivingMeta Copies/",
                      "lastWriteIso":  "2026-03-17T18:29:15.1570000+00:00",
                      "sizeBytes":  270,
                      "sizeLabel":  "0.3 KB"
                  },
                  {
                      "name":  "LivingMeta.html",
                      "category":  "Current",
                      "group":  "Finrenone LivingMeta Copies",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Finrenone LivingMeta Copies/",
                      "originalPath":  "Library/Current/Finrenone LivingMeta Copies/LivingMeta.html",
                      "copyPath":  "Library/Current/Finrenone LivingMeta Copies/LivingMeta.html",
                      "copyName":  "LivingMeta.html",
                      "folderPath":  "Library/Current/Finrenone LivingMeta Copies/",
                      "lastWriteIso":  "2026-04-23T20:16:24.5890000+01:00",
                      "sizeBytes":  965011,
                      "sizeLabel":  "942.4 KB"
                  },
                  {
                      "name":  "ABLATION_AF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/ABLATION_AF_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/ABLATION_AF_REVIEW.html",
                      "copyName":  "ABLATION_AF_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.6700000+01:00",
                      "sizeBytes":  1000403,
                      "sizeLabel":  "977.0 KB"
                  },
                  {
                      "name":  "ARNI_HF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/ARNI_HF_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/ARNI_HF_REVIEW.html",
                      "copyName":  "ARNI_HF_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.7220000+01:00",
                      "sizeBytes":  1000182,
                      "sizeLabel":  "976.7 KB"
                  },
                  {
                      "name":  "ATTR_CM_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/ATTR_CM_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/ATTR_CM_REVIEW.html",
                      "copyName":  "ATTR_CM_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.7670000+01:00",
                      "sizeBytes":  1001892,
                      "sizeLabel":  "978.4 KB"
                  },
                  {
                      "name":  "BEMPEDOIC_ACID_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/BEMPEDOIC_ACID_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/BEMPEDOIC_ACID_REVIEW.html",
                      "copyName":  "BEMPEDOIC_ACID_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.8200000+01:00",
                      "sizeBytes":  1012384,
                      "sizeLabel":  "988.7 KB"
                  },
                  {
                      "name":  "COLCHICINE_CVD_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/COLCHICINE_CVD_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/COLCHICINE_CVD_REVIEW.html",
                      "copyName":  "COLCHICINE_CVD_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.8570000+01:00",
                      "sizeBytes":  826252,
                      "sizeLabel":  "806.9 KB"
                  },
                  {
                      "name":  "DOAC_CANCER_VTE_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/DOAC_CANCER_VTE_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/DOAC_CANCER_VTE_REVIEW.html",
                      "copyName":  "DOAC_CANCER_VTE_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.9030000+01:00",
                      "sizeBytes":  999290,
                      "sizeLabel":  "975.9 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/FINERENONE_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/FINERENONE_REVIEW.html",
                      "copyName":  "FINERENONE_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:24.9520000+01:00",
                      "sizeBytes":  1016569,
                      "sizeLabel":  "992.7 KB"
                  },
                  {
                      "name":  "GLP1_CVOT_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/GLP1_CVOT_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/GLP1_CVOT_REVIEW.html",
                      "copyName":  "GLP1_CVOT_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.0130000+01:00",
                      "sizeBytes":  1116112,
                      "sizeLabel":  "1,090.0 KB"
                  },
                  {
                      "name":  "INCRETIN_HFpEF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/INCRETIN_HFpEF_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/INCRETIN_HFpEF_REVIEW.html",
                      "copyName":  "INCRETIN_HFpEF_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.0520000+01:00",
                      "sizeBytes":  1002544,
                      "sizeLabel":  "979.0 KB"
                  },
                  {
                      "name":  "INTENSIVE_BP_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/INTENSIVE_BP_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/INTENSIVE_BP_REVIEW.html",
                      "copyName":  "INTENSIVE_BP_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.0950000+01:00",
                      "sizeBytes":  998328,
                      "sizeLabel":  "974.9 KB"
                  },
                  {
                      "name":  "IV_IRON_HF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/IV_IRON_HF_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/IV_IRON_HF_REVIEW.html",
                      "copyName":  "IV_IRON_HF_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.1620000+01:00",
                      "sizeBytes":  999633,
                      "sizeLabel":  "976.2 KB"
                  },
                  {
                      "name":  "LIPID_HUB_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/LIPID_HUB_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/LIPID_HUB_REVIEW.html",
                      "copyName":  "LIPID_HUB_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.2090000+01:00",
                      "sizeBytes":  1005065,
                      "sizeLabel":  "981.5 KB"
                  },
                  {
                      "name":  "LivingMeta.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/LivingMeta.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/LivingMeta.html",
                      "copyName":  "LivingMeta.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.2510000+01:00",
                      "sizeBytes":  963432,
                      "sizeLabel":  "940.9 KB"
                  },
                  {
                      "name":  "MAVACAMTEN_HCM_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/MAVACAMTEN_HCM_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/MAVACAMTEN_HCM_REVIEW.html",
                      "copyName":  "MAVACAMTEN_HCM_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.3040000+01:00",
                      "sizeBytes":  999098,
                      "sizeLabel":  "975.7 KB"
                  },
                  {
                      "name":  "PCSK9_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/PCSK9_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/PCSK9_REVIEW.html",
                      "copyName":  "PCSK9_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.3590000+01:00",
                      "sizeBytes":  1005082,
                      "sizeLabel":  "981.5 KB"
                  },
                  {
                      "name":  "RENAL_DENERV_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/RENAL_DENERV_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/RENAL_DENERV_REVIEW.html",
                      "copyName":  "RENAL_DENERV_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.4060000+01:00",
                      "sizeBytes":  1001627,
                      "sizeLabel":  "978.2 KB"
                  },
                  {
                      "name":  "RIVAROXABAN_VASC_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/RIVAROXABAN_VASC_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/RIVAROXABAN_VASC_REVIEW.html",
                      "copyName":  "RIVAROXABAN_VASC_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.4560000+01:00",
                      "sizeBytes":  1000262,
                      "sizeLabel":  "976.8 KB"
                  },
                  {
                      "name":  "SGLT2_CKD_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/SGLT2_CKD_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/SGLT2_CKD_REVIEW.html",
                      "copyName":  "SGLT2_CKD_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.5160000+01:00",
                      "sizeBytes":  999513,
                      "sizeLabel":  "976.1 KB"
                  },
                  {
                      "name":  "SGLT2_HF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "Library/Current/Finrenone Reviews/",
                      "originalPath":  "Library/Current/Finrenone Reviews/SGLT2_HF_REVIEW.html",
                      "copyPath":  "Library/Current/Finrenone Reviews/SGLT2_HF_REVIEW.html",
                      "copyName":  "SGLT2_HF_REVIEW.html",
                      "folderPath":  "Library/Current/Finrenone Reviews/",
                      "lastWriteIso":  "2026-04-23T20:16:25.5530000+01:00",
                      "sizeBytes":  839362,
                      "sizeLabel":  "819.7 KB"
                  },
                  {
                      "name":  "AutoGRADE.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/Finrenone Support/",
                      "originalPath":  "Library/Current/Finrenone Support/AutoGRADE.html",
                      "copyPath":  "Library/Current/Finrenone Support/AutoGRADE.html",
                      "copyName":  "AutoGRADE.html",
                      "folderPath":  "Library/Current/Finrenone Support/",
                      "lastWriteIso":  "2026-04-23T20:16:25.5540000+01:00",
                      "sizeBytes":  39475,
                      "sizeLabel":  "38.5 KB"
                  },
                  {
                      "name":  "AutoManuscript.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/Finrenone Support/",
                      "originalPath":  "Library/Current/Finrenone Support/AutoManuscript.html",
                      "copyPath":  "Library/Current/Finrenone Support/AutoManuscript.html",
                      "copyName":  "AutoManuscript.html",
                      "folderPath":  "Library/Current/Finrenone Support/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4350000+01:00",
                      "sizeBytes":  45773,
                      "sizeLabel":  "44.7 KB"
                  },
                  {
                      "name":  "META_DASHBOARD.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/Finrenone Support/",
                      "originalPath":  "Library/Current/Finrenone Support/META_DASHBOARD.html",
                      "copyPath":  "Library/Current/Finrenone Support/META_DASHBOARD.html",
                      "copyName":  "META_DASHBOARD.html",
                      "folderPath":  "Library/Current/Finrenone Support/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4390000+01:00",
                      "sizeBytes":  70742,
                      "sizeLabel":  "69.1 KB"
                  },
                  {
                      "name":  "MetaExtract.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/Finrenone Support/",
                      "originalPath":  "Library/Current/Finrenone Support/MetaExtract.html",
                      "copyPath":  "Library/Current/Finrenone Support/MetaExtract.html",
                      "copyName":  "MetaExtract.html",
                      "folderPath":  "Library/Current/Finrenone Support/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4370000+01:00",
                      "sizeBytes":  16051,
                      "sizeLabel":  "15.7 KB"
                  },
                  {
                      "name":  "TrialRadar.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/Finrenone Support/",
                      "originalPath":  "Library/Current/Finrenone Support/TrialRadar.html",
                      "copyPath":  "Library/Current/Finrenone Support/TrialRadar.html",
                      "copyName":  "TrialRadar.html",
                      "folderPath":  "Library/Current/Finrenone Support/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4390000+01:00",
                      "sizeBytes":  20332,
                      "sizeLabel":  "19.9 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "Living Meta App",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Living Meta App/",
                      "originalPath":  "Library/Current/Living Meta App/index.html",
                      "copyPath":  "Library/Current/Living Meta App/index.html",
                      "copyName":  "index.html",
                      "folderPath":  "Library/Current/Living Meta App/",
                      "lastWriteIso":  "2026-03-28T14:59:59.1340000+00:00",
                      "sizeBytes":  3922,
                      "sizeLabel":  "3.8 KB"
                  },
                  {
                      "name":  "living-meta-complete.html",
                      "category":  "Current",
                      "group":  "Living Meta App",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Living Meta App/",
                      "originalPath":  "Library/Current/Living Meta App/living-meta-complete.html",
                      "copyPath":  "Library/Current/Living Meta App/living-meta-complete.html",
                      "copyName":  "living-meta-complete.html",
                      "folderPath":  "Library/Current/Living Meta App/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4450000+01:00",
                      "sizeBytes":  120552,
                      "sizeLabel":  "117.7 KB"
                  },
                  {
                      "name":  "living-meta-engine.html",
                      "category":  "Current",
                      "group":  "Living Meta Engine",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Living Meta Engine/",
                      "originalPath":  "Library/Current/Living Meta Engine/living-meta-engine.html",
                      "copyPath":  "Library/Current/Living Meta Engine/living-meta-engine.html",
                      "copyName":  "living-meta-engine.html",
                      "folderPath":  "Library/Current/Living Meta Engine/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4470000+01:00",
                      "sizeBytes":  49946,
                      "sizeLabel":  "48.8 KB"
                  },
                  {
                      "name":  "living-meta-standalone.html",
                      "category":  "Current",
                      "group":  "Living Meta Standalone App",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Living Meta Standalone App/",
                      "originalPath":  "Library/Current/Living Meta Standalone App/living-meta-standalone.html",
                      "copyPath":  "Library/Current/Living Meta Standalone App/living-meta-standalone.html",
                      "copyName":  "living-meta-standalone.html",
                      "folderPath":  "Library/Current/Living Meta Standalone App/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4500000+01:00",
                      "sizeBytes":  30860,
                      "sizeLabel":  "30.1 KB"
                  },
                  {
                      "name":  "PFA_AF_LivingMeta.html",
                      "category":  "Current",
                      "group":  "PFA AF Living Meta",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/PFA AF Living Meta/",
                      "originalPath":  "Library/Current/PFA AF Living Meta/PFA_AF_LivingMeta.html",
                      "copyPath":  "Library/Current/PFA AF Living Meta/PFA_AF_LivingMeta.html",
                      "copyName":  "PFA_AF_LivingMeta.html",
                      "folderPath":  "Library/Current/PFA AF Living Meta/",
                      "lastWriteIso":  "2026-04-23T20:16:25.5890000+01:00",
                      "sizeBytes":  216719,
                      "sizeLabel":  "211.6 KB"
                  },
                  {
                      "name":  "dashboard.html",
                      "category":  "Current",
                      "group":  "TEER Support",
                      "kind":  "Support",
                      "sourceRoot":  "Library/Current/TEER Support/",
                      "originalPath":  "Library/Current/TEER Support/dashboard.html",
                      "copyPath":  "Library/Current/TEER Support/dashboard.html",
                      "copyName":  "dashboard.html",
                      "folderPath":  "Library/Current/TEER Support/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4630000+01:00",
                      "sizeBytes":  6664,
                      "sizeLabel":  "6.5 KB"
                  },
                  {
                      "name":  "TEER_LIVING_META.html",
                      "category":  "Current",
                      "group":  "Tricuspid TEER Living Meta",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Tricuspid TEER Living Meta/",
                      "originalPath":  "Library/Current/Tricuspid TEER Living Meta/TEER_LIVING_META.html",
                      "copyPath":  "Library/Current/Tricuspid TEER Living Meta/TEER_LIVING_META.html",
                      "copyName":  "TEER_LIVING_META.html",
                      "folderPath":  "Library/Current/Tricuspid TEER Living Meta/",
                      "lastWriteIso":  "2026-04-23T20:16:25.6090000+01:00",
                      "sizeBytes":  270094,
                      "sizeLabel":  "263.8 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "Watchman and Amulet",
                      "kind":  "App",
                      "sourceRoot":  "Library/Current/Watchman and Amulet/",
                      "originalPath":  "Library/Current/Watchman and Amulet/index.html",
                      "copyPath":  "Library/Current/Watchman and Amulet/index.html",
                      "copyName":  "index.html",
                      "folderPath":  "Library/Current/Watchman and Amulet/",
                      "lastWriteIso":  "2026-04-23T20:07:28.4840000+01:00",
                      "sizeBytes":  268731,
                      "sizeLabel":  "262.4 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.html",
                      "category":  "Legacy",
                      "group":  "Legacy Root Copies",
                      "kind":  "Legacy",
                      "sourceRoot":  "Library/Legacy/Legacy Root Copies/",
                      "originalPath":  "Library/Legacy/Legacy Root Copies/FINERENONE_REVIEW.html",
                      "copyPath":  "Library/Legacy/Legacy Root Copies/FINERENONE_REVIEW.html",
                      "copyName":  "FINERENONE_REVIEW.html",
                      "folderPath":  "Library/Legacy/Legacy Root Copies/",
                      "lastWriteIso":  "2026-04-23T20:16:24.5450000+01:00",
                      "sizeBytes":  599540,
                      "sizeLabel":  "585.5 KB"
                  },
                  {
                      "name":  ".superpowers -- brainstorm -- 87465-1773150054 -- sglt2-gaps-overview.html",
                      "category":  "Scratch",
                      "group":  "Finrenone Experiments",
                      "kind":  "Scratch",
                      "sourceRoot":  "Library/Scratch/Finrenone Experiments/",
                      "originalPath":  "Library/Scratch/Finrenone Experiments/.superpowers -- brainstorm -- 87465-1773150054 -- sglt2-gaps-overview.html",
                      "copyPath":  "Library/Scratch/Finrenone Experiments/.superpowers -- brainstorm -- 87465-1773150054 -- sglt2-gaps-overview.html",
                      "copyName":  ".superpowers -- brainstorm -- 87465-1773150054 -- sglt2-gaps-overview.html",
                      "folderPath":  "Library/Scratch/Finrenone Experiments/",
                      "lastWriteIso":  "2026-03-10T13:42:14.9080000+00:00",
                      "sizeBytes":  7580,
                      "sizeLabel":  "7.4 KB"
                  },
                  {
                      "name":  "vnext -- CRYO_AF_REVIEW_VNEXT.html",
                      "category":  "Scratch",
                      "group":  "Finrenone Experiments",
                      "kind":  "Scratch",
                      "sourceRoot":  "Library/Scratch/Finrenone Experiments/",
                      "originalPath":  "Library/Scratch/Finrenone Experiments/vnext -- CRYO_AF_REVIEW_VNEXT.html",
                      "copyPath":  "Library/Scratch/Finrenone Experiments/vnext -- CRYO_AF_REVIEW_VNEXT.html",
                      "copyName":  "vnext -- CRYO_AF_REVIEW_VNEXT.html",
                      "folderPath":  "Library/Scratch/Finrenone Experiments/",
                      "lastWriteIso":  "2026-04-23T20:16:24.4950000+01:00",
                      "sizeBytes":  122467,
                      "sizeLabel":  "119.6 KB"
                  },
                  {
                      "name":  "vnext -- FINERENONE_REVIEW_VNEXT.html",
                      "category":  "Scratch",
                      "group":  "Finrenone Experiments",
                      "kind":  "Scratch",
                      "sourceRoot":  "Library/Scratch/Finrenone Experiments/",
                      "originalPath":  "Library/Scratch/Finrenone Experiments/vnext -- FINERENONE_REVIEW_VNEXT.html",
                      "copyPath":  "Library/Scratch/Finrenone Experiments/vnext -- FINERENONE_REVIEW_VNEXT.html",
                      "copyName":  "vnext -- FINERENONE_REVIEW_VNEXT.html",
                      "folderPath":  "Library/Scratch/Finrenone Experiments/",
                      "lastWriteIso":  "2026-04-23T20:16:24.5010000+01:00",
                      "sizeBytes":  122068,
                      "sizeLabel":  "119.2 KB"
                  },
                  {
                      "name":  "teer (3).html",
                      "category":  "Scratch",
                      "group":  "TEER Scratch",
                      "kind":  "Scratch",
                      "sourceRoot":  "Library/Scratch/TEER Scratch/",
                      "originalPath":  "Library/Scratch/TEER Scratch/teer (3).html",
                      "copyPath":  "Library/Scratch/TEER Scratch/teer (3).html",
                      "copyName":  "teer (3).html",
                      "folderPath":  "Library/Scratch/TEER Scratch/",
                      "lastWriteIso":  "2025-11-28T21:06:06.5810000+00:00",
                      "sizeBytes":  46561,
                      "sizeLabel":  "45.5 KB"
                  },
                  {
                      "name":  "teer.html",
                      "category":  "Scratch",
                      "group":  "TEER Scratch",
                      "kind":  "Scratch",
                      "sourceRoot":  "Library/Scratch/TEER Scratch/",
                      "originalPath":  "Library/Scratch/TEER Scratch/teer.html",
                      "copyPath":  "Library/Scratch/TEER Scratch/teer.html",
                      "copyName":  "teer.html",
                      "folderPath":  "Library/Scratch/TEER Scratch/",
                      "lastWriteIso":  "2025-11-28T13:08:13.0770000+00:00",
                      "sizeBytes":  46561,
                      "sizeLabel":  "45.5 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- ABLATION_AF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ABLATION_AF_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ABLATION_AF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- ABLATION_AF_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.3530000+01:00",
                      "sizeBytes":  1000403,
                      "sizeLabel":  "977.0 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- ARNI_HF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ARNI_HF_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ARNI_HF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- ARNI_HF_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.3910000+01:00",
                      "sizeBytes":  1000182,
                      "sizeLabel":  "976.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- ATTR_CM_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ATTR_CM_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ATTR_CM_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- ATTR_CM_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.4310000+01:00",
                      "sizeBytes":  1001892,
                      "sizeLabel":  "978.4 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- ATTR_CM_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ATTR_CM_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- ATTR_CM_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- ATTR_CM_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:26.8820000+01:00",
                      "sizeBytes":  27518,
                      "sizeLabel":  "26.9 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- AutoGRADE.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- AutoGRADE.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- AutoGRADE.html",
                      "copyName":  "e156-submission -- assets -- AutoGRADE.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.4470000+01:00",
                      "sizeBytes":  39475,
                      "sizeLabel":  "38.5 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- AutoManuscript.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- AutoManuscript.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- AutoManuscript.html",
                      "copyName":  "e156-submission -- assets -- AutoManuscript.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:26.8880000+01:00",
                      "sizeBytes":  45773,
                      "sizeLabel":  "44.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- BEMPEDOIC_ACID_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- BEMPEDOIC_ACID_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- BEMPEDOIC_ACID_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- BEMPEDOIC_ACID_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.4890000+01:00",
                      "sizeBytes":  1012384,
                      "sizeLabel":  "988.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- COLCHICINE_CVD_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- COLCHICINE_CVD_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- COLCHICINE_CVD_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- COLCHICINE_CVD_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.5260000+01:00",
                      "sizeBytes":  826252,
                      "sizeLabel":  "806.9 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.5590000+01:00",
                      "sizeBytes":  817575,
                      "sizeLabel":  "798.4 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- DOAC_CANCER_VTE_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- DOAC_CANCER_VTE_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- DOAC_CANCER_VTE_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- DOAC_CANCER_VTE_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.5930000+01:00",
                      "sizeBytes":  999290,
                      "sizeLabel":  "975.9 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- FINERENONE_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- FINERENONE_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- FINERENONE_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- FINERENONE_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.6380000+01:00",
                      "sizeBytes":  1016569,
                      "sizeLabel":  "992.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyName":  "e156-submission -- assets -- FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.6530000+01:00",
                      "sizeBytes":  661103,
                      "sizeLabel":  "645.6 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- GLP1_CVOT_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- GLP1_CVOT_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- GLP1_CVOT_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- GLP1_CVOT_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.7330000+01:00",
                      "sizeBytes":  1116112,
                      "sizeLabel":  "1,090.0 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- GLP1_CVOT_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- GLP1_CVOT_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.8160000+01:00",
                      "sizeBytes":  1107435,
                      "sizeLabel":  "1,081.5 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.8790000+01:00",
                      "sizeBytes":  1002544,
                      "sizeLabel":  "979.0 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.1680000+01:00",
                      "sizeBytes":  430822,
                      "sizeLabel":  "420.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- INTENSIVE_BP_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- INTENSIVE_BP_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- INTENSIVE_BP_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- INTENSIVE_BP_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.9460000+01:00",
                      "sizeBytes":  998328,
                      "sizeLabel":  "974.9 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- IV_IRON_HF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- IV_IRON_HF_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- IV_IRON_HF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- IV_IRON_HF_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:23.9950000+01:00",
                      "sizeBytes":  999633,
                      "sizeLabel":  "976.2 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- LIPID_HUB_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- LIPID_HUB_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- LIPID_HUB_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- LIPID_HUB_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.0460000+01:00",
                      "sizeBytes":  1005065,
                      "sizeLabel":  "981.5 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- LivingMeta.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- LivingMeta.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- LivingMeta.html",
                      "copyName":  "e156-submission -- assets -- LivingMeta.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.1140000+01:00",
                      "sizeBytes":  963432,
                      "sizeLabel":  "940.9 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- MAVACAMTEN_HCM_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- MAVACAMTEN_HCM_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- MAVACAMTEN_HCM_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- MAVACAMTEN_HCM_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.1710000+01:00",
                      "sizeBytes":  999098,
                      "sizeLabel":  "975.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- META_DASHBOARD.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- META_DASHBOARD.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- META_DASHBOARD.html",
                      "copyName":  "e156-submission -- assets -- META_DASHBOARD.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.3580000+01:00",
                      "sizeBytes":  70742,
                      "sizeLabel":  "69.1 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- MetaExtract.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- MetaExtract.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- MetaExtract.html",
                      "copyName":  "e156-submission -- assets -- MetaExtract.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.3410000+01:00",
                      "sizeBytes":  16051,
                      "sizeLabel":  "15.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- PCSK9_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- PCSK9_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- PCSK9_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- PCSK9_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.2260000+01:00",
                      "sizeBytes":  1005082,
                      "sizeLabel":  "981.5 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- RENAL_DENERV_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- RENAL_DENERV_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- RENAL_DENERV_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- RENAL_DENERV_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.2830000+01:00",
                      "sizeBytes":  1001627,
                      "sizeLabel":  "978.2 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- RIVAROXABAN_VASC_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- RIVAROXABAN_VASC_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- RIVAROXABAN_VASC_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- RIVAROXABAN_VASC_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.3370000+01:00",
                      "sizeBytes":  1000262,
                      "sizeLabel":  "976.8 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- SGLT2_CKD_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- SGLT2_CKD_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- SGLT2_CKD_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- SGLT2_CKD_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.3890000+01:00",
                      "sizeBytes":  999513,
                      "sizeLabel":  "976.1 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- SGLT2_HF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- SGLT2_HF_REVIEW.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- SGLT2_HF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- SGLT2_HF_REVIEW.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.4370000+01:00",
                      "sizeBytes":  839362,
                      "sizeLabel":  "819.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- SGLT2_HF_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- SGLT2_HF_REVIEW.v11.bak.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- SGLT2_HF_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- SGLT2_HF_REVIEW.v11.bak.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:16:24.4780000+01:00",
                      "sizeBytes":  830685,
                      "sizeLabel":  "811.2 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- TrialRadar.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- TrialRadar.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- assets -- TrialRadar.html",
                      "copyName":  "e156-submission -- assets -- TrialRadar.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.5550000+01:00",
                      "sizeBytes":  20332,
                      "sizeLabel":  "19.9 KB"
                  },
                  {
                      "name":  "e156-submission -- index.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Finrenone E156 Submission/",
                      "originalPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- index.html",
                      "copyPath":  "Library/Submission/Finrenone E156 Submission/e156-submission -- index.html",
                      "copyName":  "e156-submission -- index.html",
                      "folderPath":  "Library/Submission/Finrenone E156 Submission/",
                      "lastWriteIso":  "2026-03-28T11:38:46.8510000+00:00",
                      "sizeBytes":  24042,
                      "sizeLabel":  "23.5 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- index.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Living Meta App E156 Submission/",
                      "originalPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- assets -- index.html",
                      "copyPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- assets -- index.html",
                      "copyName":  "e156-submission -- assets -- index.html",
                      "folderPath":  "Library/Submission/Living Meta App E156 Submission/",
                      "lastWriteIso":  "2026-01-02T01:28:57.3520000+00:00",
                      "sizeBytes":  3685,
                      "sizeLabel":  "3.6 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- living-meta-complete.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Living Meta App E156 Submission/",
                      "originalPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- assets -- living-meta-complete.html",
                      "copyPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- assets -- living-meta-complete.html",
                      "copyName":  "e156-submission -- assets -- living-meta-complete.html",
                      "folderPath":  "Library/Submission/Living Meta App E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.5660000+01:00",
                      "sizeBytes":  120552,
                      "sizeLabel":  "117.7 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- living-meta-standalone.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Living Meta App E156 Submission/",
                      "originalPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- assets -- living-meta-standalone.html",
                      "copyPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- assets -- living-meta-standalone.html",
                      "copyName":  "e156-submission -- assets -- living-meta-standalone.html",
                      "folderPath":  "Library/Submission/Living Meta App E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.5660000+01:00",
                      "sizeBytes":  30860,
                      "sizeLabel":  "30.1 KB"
                  },
                  {
                      "name":  "e156-submission -- index.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Living Meta App E156 Submission/",
                      "originalPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- index.html",
                      "copyPath":  "Library/Submission/Living Meta App E156 Submission/e156-submission -- index.html",
                      "copyName":  "e156-submission -- index.html",
                      "folderPath":  "Library/Submission/Living Meta App E156 Submission/",
                      "lastWriteIso":  "2026-03-28T11:38:44.5660000+00:00",
                      "sizeBytes":  22926,
                      "sizeLabel":  "22.4 KB"
                  },
                  {
                      "name":  "e156-submission -- assets -- living-meta-engine.html",
                      "category":  "Submission",
                      "group":  "Living Meta Engine E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Living Meta Engine E156 Submission/",
                      "originalPath":  "Library/Submission/Living Meta Engine E156 Submission/e156-submission -- assets -- living-meta-engine.html",
                      "copyPath":  "Library/Submission/Living Meta Engine E156 Submission/e156-submission -- assets -- living-meta-engine.html",
                      "copyName":  "e156-submission -- assets -- living-meta-engine.html",
                      "folderPath":  "Library/Submission/Living Meta Engine E156 Submission/",
                      "lastWriteIso":  "2026-04-23T20:07:27.5710000+01:00",
                      "sizeBytes":  45801,
                      "sizeLabel":  "44.7 KB"
                  },
                  {
                      "name":  "e156-submission -- index.html",
                      "category":  "Submission",
                      "group":  "Living Meta Engine E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "Library/Submission/Living Meta Engine E156 Submission/",
                      "originalPath":  "Library/Submission/Living Meta Engine E156 Submission/e156-submission -- index.html",
                      "copyPath":  "Library/Submission/Living Meta Engine E156 Submission/e156-submission -- index.html",
                      "copyName":  "e156-submission -- index.html",
                      "folderPath":  "Library/Submission/Living Meta Engine E156 Submission/",
                      "lastWriteIso":  "2026-03-28T12:39:12.5920000+00:00",
                      "sizeBytes":  21960,
                      "sizeLabel":  "21.4 KB"
                  }
              ]
};