window.LIVING_META_LIBRARY = {
    "generatedAt":  "2026-03-28T15:02:39.8488006+00:00",
    "items":  [
                  {
                      "name":  "ATTR_CM_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\ATTR_CM_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\ATTR_CM_REVIEW.v11.bak.html",
                      "copyName":  "ATTR_CM_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-14T22:06:50.7115452+00:00",
                      "sizeBytes":  27495,
                      "sizeLabel":  "26.9 KB"
                  },
                  {
                      "name":  "COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyName":  "COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-18T07:13:17.1956855+00:00",
                      "sizeBytes":  816955,
                      "sizeLabel":  "797.8 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyName":  "FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "lastWriteIso":  "2026-03-10T14:58:10.1886641+00:00",
                      "sizeBytes":  659847,
                      "sizeLabel":  "644.4 KB"
                  },
                  {
                      "name":  "GLP1_CVOT_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyName":  "GLP1_CVOT_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-18T07:13:30.5501045+00:00",
                      "sizeBytes":  1106815,
                      "sizeLabel":  "1,080.9 KB"
                  },
                  {
                      "name":  "INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyName":  "INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-14T22:17:10.0153410+00:00",
                      "sizeBytes":  430644,
                      "sizeLabel":  "420.6 KB"
                  },
                  {
                      "name":  "LivingMeta_backup.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\livingmeta\\LivingMeta_backup.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\livingmeta -- LivingMeta_backup.html",
                      "copyName":  "livingmeta -- LivingMeta_backup.html",
                      "lastWriteIso":  "2026-03-18T11:13:06.5295842+00:00",
                      "sizeBytes":  962565,
                      "sizeLabel":  "940.0 KB"
                  },
                  {
                      "name":  "LivingMeta_backup2.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\livingmeta\\LivingMeta_backup2.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\livingmeta -- LivingMeta_backup2.html",
                      "copyName":  "livingmeta -- LivingMeta_backup2.html",
                      "lastWriteIso":  "2026-03-18T15:50:05.1017097+00:00",
                      "sizeBytes":  964351,
                      "sizeLabel":  "941.7 KB"
                  },
                  {
                      "name":  "SGLT2_HF_REVIEW.v11.bak.html",
                      "category":  "Backup",
                      "group":  "Finrenone Backups",
                      "kind":  "Backup",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\SGLT2_HF_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Backup\\Finrenone Backups\\SGLT2_HF_REVIEW.v11.bak.html",
                      "copyName":  "SGLT2_HF_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-18T07:13:46.2169187+00:00",
                      "sizeBytes":  830064,
                      "sizeLabel":  "810.6 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "ESC ACS Living Meta",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\esc-acs-living-meta",
                      "originalPath":  "C:\\Projects\\esc-acs-living-meta\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\ESC ACS Living Meta\\index.html",
                      "copyName":  "index.html",
                      "lastWriteIso":  "2026-01-26T20:30:07.9123773+00:00",
                      "sizeBytes":  31623,
                      "sizeLabel":  "30.9 KB"
                  },
                  {
                      "name":  "r-validation-runner.html",
                      "category":  "Current",
                      "group":  "ESC ACS Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\esc-acs-living-meta",
                      "originalPath":  "C:\\Projects\\esc-acs-living-meta\\r-validation-runner.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\ESC ACS Support\\r-validation-runner.html",
                      "copyName":  "r-validation-runner.html",
                      "lastWriteIso":  "2026-01-26T10:11:35.7406430+00:00",
                      "sizeBytes":  14161,
                      "sizeLabel":  "13.8 KB"
                  },
                  {
                      "name":  "test-runner.html",
                      "category":  "Current",
                      "group":  "ESC ACS Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\esc-acs-living-meta",
                      "originalPath":  "C:\\Projects\\esc-acs-living-meta\\test-runner.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\ESC ACS Support\\test-runner.html",
                      "copyName":  "test-runner.html",
                      "lastWriteIso":  "2026-01-26T10:11:54.3074152+00:00",
                      "sizeBytes":  3759,
                      "sizeLabel":  "3.7 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "Finrenone LivingMeta Copies",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\livingmeta\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone LivingMeta Copies\\index.html",
                      "copyName":  "index.html",
                      "lastWriteIso":  "2026-03-17T18:29:15.1577534+00:00",
                      "sizeBytes":  270,
                      "sizeLabel":  "0.3 KB"
                  },
                  {
                      "name":  "LivingMeta.html",
                      "category":  "Current",
                      "group":  "Finrenone LivingMeta Copies",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\livingmeta\\LivingMeta.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone LivingMeta Copies\\LivingMeta.html",
                      "copyName":  "LivingMeta.html",
                      "lastWriteIso":  "2026-03-18T15:49:00.5851674+00:00",
                      "sizeBytes":  964351,
                      "sizeLabel":  "941.7 KB"
                  },
                  {
                      "name":  "ABLATION_AF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\ABLATION_AF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\ABLATION_AF_REVIEW.html",
                      "copyName":  "ABLATION_AF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.2161842+00:00",
                      "sizeBytes":  999778,
                      "sizeLabel":  "976.3 KB"
                  },
                  {
                      "name":  "ARNI_HF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\ARNI_HF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\ARNI_HF_REVIEW.html",
                      "copyName":  "ARNI_HF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.2507618+00:00",
                      "sizeBytes":  999557,
                      "sizeLabel":  "976.1 KB"
                  },
                  {
                      "name":  "ATTR_CM_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\ATTR_CM_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\ATTR_CM_REVIEW.html",
                      "copyName":  "ATTR_CM_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.2805297+00:00",
                      "sizeBytes":  1001267,
                      "sizeLabel":  "977.8 KB"
                  },
                  {
                      "name":  "BEMPEDOIC_ACID_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\BEMPEDOIC_ACID_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\BEMPEDOIC_ACID_REVIEW.html",
                      "copyName":  "BEMPEDOIC_ACID_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.3237766+00:00",
                      "sizeBytes":  1011759,
                      "sizeLabel":  "988.0 KB"
                  },
                  {
                      "name":  "COLCHICINE_CVD_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\COLCHICINE_CVD_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\COLCHICINE_CVD_REVIEW.html",
                      "copyName":  "COLCHICINE_CVD_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:48:49.7183824+00:00",
                      "sizeBytes":  825632,
                      "sizeLabel":  "806.3 KB"
                  },
                  {
                      "name":  "DOAC_CANCER_VTE_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\DOAC_CANCER_VTE_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\DOAC_CANCER_VTE_REVIEW.html",
                      "copyName":  "DOAC_CANCER_VTE_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.3799484+00:00",
                      "sizeBytes":  998665,
                      "sizeLabel":  "975.3 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\FINERENONE_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\FINERENONE_REVIEW.html",
                      "copyName":  "FINERENONE_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.4246239+00:00",
                      "sizeBytes":  1015944,
                      "sizeLabel":  "992.1 KB"
                  },
                  {
                      "name":  "GLP1_CVOT_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\GLP1_CVOT_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\GLP1_CVOT_REVIEW.html",
                      "copyName":  "GLP1_CVOT_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:48:50.1624039+00:00",
                      "sizeBytes":  1115492,
                      "sizeLabel":  "1,089.3 KB"
                  },
                  {
                      "name":  "INCRETIN_HFpEF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\INCRETIN_HFpEF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\INCRETIN_HFpEF_REVIEW.html",
                      "copyName":  "INCRETIN_HFpEF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.4773071+00:00",
                      "sizeBytes":  1001919,
                      "sizeLabel":  "978.4 KB"
                  },
                  {
                      "name":  "INTENSIVE_BP_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\INTENSIVE_BP_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\INTENSIVE_BP_REVIEW.html",
                      "copyName":  "INTENSIVE_BP_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:54:28.0977983+00:00",
                      "sizeBytes":  997648,
                      "sizeLabel":  "974.3 KB"
                  },
                  {
                      "name":  "IV_IRON_HF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\IV_IRON_HF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\IV_IRON_HF_REVIEW.html",
                      "copyName":  "IV_IRON_HF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.5456056+00:00",
                      "sizeBytes":  999008,
                      "sizeLabel":  "975.6 KB"
                  },
                  {
                      "name":  "LIPID_HUB_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\LIPID_HUB_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\LIPID_HUB_REVIEW.html",
                      "copyName":  "LIPID_HUB_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:54:28.1285090+00:00",
                      "sizeBytes":  1004442,
                      "sizeLabel":  "980.9 KB"
                  },
                  {
                      "name":  "LivingMeta.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\LivingMeta.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\LivingMeta.html",
                      "copyName":  "LivingMeta.html",
                      "lastWriteIso":  "2026-03-18T12:16:38.6564042+00:00",
                      "sizeBytes":  962645,
                      "sizeLabel":  "940.1 KB"
                  },
                  {
                      "name":  "MAVACAMTEN_HCM_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\MAVACAMTEN_HCM_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\MAVACAMTEN_HCM_REVIEW.html",
                      "copyName":  "MAVACAMTEN_HCM_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.6229998+00:00",
                      "sizeBytes":  998473,
                      "sizeLabel":  "975.1 KB"
                  },
                  {
                      "name":  "PCSK9_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\PCSK9_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\PCSK9_REVIEW.html",
                      "copyName":  "PCSK9_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.6623159+00:00",
                      "sizeBytes":  1004457,
                      "sizeLabel":  "980.9 KB"
                  },
                  {
                      "name":  "RENAL_DENERV_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\RENAL_DENERV_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\RENAL_DENERV_REVIEW.html",
                      "copyName":  "RENAL_DENERV_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.6915915+00:00",
                      "sizeBytes":  1001002,
                      "sizeLabel":  "977.5 KB"
                  },
                  {
                      "name":  "RIVAROXABAN_VASC_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\RIVAROXABAN_VASC_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\RIVAROXABAN_VASC_REVIEW.html",
                      "copyName":  "RIVAROXABAN_VASC_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.7254603+00:00",
                      "sizeBytes":  999637,
                      "sizeLabel":  "976.2 KB"
                  },
                  {
                      "name":  "SGLT2_CKD_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\SGLT2_CKD_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\SGLT2_CKD_REVIEW.html",
                      "copyName":  "SGLT2_CKD_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.7706129+00:00",
                      "sizeBytes":  998888,
                      "sizeLabel":  "975.5 KB"
                  },
                  {
                      "name":  "SGLT2_HF_REVIEW.html",
                      "category":  "Current",
                      "group":  "Finrenone Reviews",
                      "kind":  "Review",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\SGLT2_HF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Reviews\\SGLT2_HF_REVIEW.html",
                      "copyName":  "SGLT2_HF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:48:51.6964910+00:00",
                      "sizeBytes":  838741,
                      "sizeLabel":  "819.1 KB"
                  },
                  {
                      "name":  "AutoGRADE.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\AutoGRADE.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Support\\AutoGRADE.html",
                      "copyName":  "AutoGRADE.html",
                      "lastWriteIso":  "2026-03-15T14:37:19.8969631+00:00",
                      "sizeBytes":  38750,
                      "sizeLabel":  "37.8 KB"
                  },
                  {
                      "name":  "AutoManuscript.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\AutoManuscript.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Support\\AutoManuscript.html",
                      "copyName":  "AutoManuscript.html",
                      "lastWriteIso":  "2026-03-18T07:00:58.5139278+00:00",
                      "sizeBytes":  44739,
                      "sizeLabel":  "43.7 KB"
                  },
                  {
                      "name":  "META_DASHBOARD.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\META_DASHBOARD.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Support\\META_DASHBOARD.html",
                      "copyName":  "META_DASHBOARD.html",
                      "lastWriteIso":  "2026-03-18T06:59:40.9208409+00:00",
                      "sizeBytes":  69180,
                      "sizeLabel":  "67.6 KB"
                  },
                  {
                      "name":  "MetaExtract.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\MetaExtract.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Support\\MetaExtract.html",
                      "copyName":  "MetaExtract.html",
                      "lastWriteIso":  "2026-03-15T14:37:19.9652727+00:00",
                      "sizeBytes":  15760,
                      "sizeLabel":  "15.4 KB"
                  },
                  {
                      "name":  "TrialRadar.html",
                      "category":  "Current",
                      "group":  "Finrenone Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\TrialRadar.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Finrenone Support\\TrialRadar.html",
                      "copyName":  "TrialRadar.html",
                      "lastWriteIso":  "2026-03-15T14:37:19.9303603+00:00",
                      "sizeBytes":  20302,
                      "sizeLabel":  "19.8 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "Living Meta App",
                      "kind":  "App",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Living Meta App\\index.html",
                      "copyName":  "index.html",
                      "lastWriteIso":  "2026-01-02T01:28:57.3523350+00:00",
                      "sizeBytes":  3685,
                      "sizeLabel":  "3.6 KB"
                  },
                  {
                      "name":  "living-meta-complete.html",
                      "category":  "Current",
                      "group":  "Living Meta App",
                      "kind":  "App",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\living-meta-complete.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Living Meta App\\living-meta-complete.html",
                      "copyName":  "living-meta-complete.html",
                      "lastWriteIso":  "2026-01-19T22:41:12.4452813+00:00",
                      "sizeBytes":  120450,
                      "sizeLabel":  "117.6 KB"
                  },
                  {
                      "name":  "living-meta-engine.html",
                      "category":  "Current",
                      "group":  "Living Meta Engine",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\living-meta-engine",
                      "originalPath":  "C:\\Projects\\living-meta-engine\\living-meta-engine.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Living Meta Engine\\living-meta-engine.html",
                      "copyName":  "living-meta-engine.html",
                      "lastWriteIso":  "2026-03-25T16:24:18.5823525+00:00",
                      "sizeBytes":  44797,
                      "sizeLabel":  "43.7 KB"
                  },
                  {
                      "name":  "living-meta-standalone.html",
                      "category":  "Current",
                      "group":  "Living Meta Standalone App",
                      "kind":  "App",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\dist-single\\living-meta-standalone.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Living Meta Standalone App\\living-meta-standalone.html",
                      "copyName":  "living-meta-standalone.html",
                      "lastWriteIso":  "2026-01-14T23:10:11.9142636+00:00",
                      "sizeBytes":  30693,
                      "sizeLabel":  "30.0 KB"
                  },
                  {
                      "name":  "PFA_AF_LivingMeta.html",
                      "category":  "Current",
                      "group":  "PFA AF Living Meta",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\PFA_AF_LivingMeta",
                      "originalPath":  "C:\\Projects\\PFA_AF_LivingMeta\\PFA_AF_LivingMeta.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\PFA AF Living Meta\\PFA_AF_LivingMeta.html",
                      "copyName":  "PFA_AF_LivingMeta.html",
                      "lastWriteIso":  "2026-03-24T12:59:46.7395339+00:00",
                      "sizeBytes":  197047,
                      "sizeLabel":  "192.4 KB"
                  },
                  {
                      "name":  "dashboard.html",
                      "category":  "Current",
                      "group":  "TEER Support",
                      "kind":  "Support",
                      "sourceRoot":  "C:\\Projects\\Tricuspid_TEER_LivingMeta",
                      "originalPath":  "C:\\Projects\\Tricuspid_TEER_LivingMeta\\dashboard.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\TEER Support\\dashboard.html",
                      "copyName":  "dashboard.html",
                      "lastWriteIso":  "2026-03-24T13:05:21.6239291+00:00",
                      "sizeBytes":  6613,
                      "sizeLabel":  "6.5 KB"
                  },
                  {
                      "name":  "TEER_LIVING_META.html",
                      "category":  "Current",
                      "group":  "Tricuspid TEER Living Meta",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\Tricuspid_TEER_LivingMeta",
                      "originalPath":  "C:\\Projects\\Tricuspid_TEER_LivingMeta\\TEER_LIVING_META.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Tricuspid TEER Living Meta\\TEER_LIVING_META.html",
                      "copyName":  "TEER_LIVING_META.html",
                      "lastWriteIso":  "2026-03-24T13:05:21.3750218+00:00",
                      "sizeBytes":  252243,
                      "sizeLabel":  "246.3 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Current",
                      "group":  "Watchman and Amulet",
                      "kind":  "App",
                      "sourceRoot":  "C:\\Projects\\LivingMeta_Watchman_Amulet",
                      "originalPath":  "C:\\Projects\\LivingMeta_Watchman_Amulet\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Current\\Watchman and Amulet\\index.html",
                      "copyName":  "index.html",
                      "lastWriteIso":  "2026-03-24T12:49:00.0954778+00:00",
                      "sizeBytes":  248179,
                      "sizeLabel":  "242.4 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.html",
                      "category":  "Legacy",
                      "group":  "Legacy Root Copies",
                      "kind":  "Legacy",
                      "sourceRoot":  "C:\\Living metas",
                      "originalPath":  "C:\\Living metas\\FINERENONE_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Legacy\\Legacy Root Copies\\FINERENONE_REVIEW.html",
                      "copyName":  "FINERENONE_REVIEW.html",
                      "lastWriteIso":  "2026-03-04T15:58:56.4372862+00:00",
                      "sizeBytes":  596327,
                      "sizeLabel":  "582.4 KB"
                  },
                  {
                      "name":  "sglt2-gaps-overview.html",
                      "category":  "Scratch",
                      "group":  "Finrenone Experiments",
                      "kind":  "Scratch",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\.superpowers\\brainstorm\\87465-1773150054\\sglt2-gaps-overview.html",
                      "copyPath":  "C:\\Living metas\\Library\\Scratch\\Finrenone Experiments\\.superpowers -- brainstorm -- 87465-1773150054 -- sglt2-gaps-overview.html",
                      "copyName":  ".superpowers -- brainstorm -- 87465-1773150054 -- sglt2-gaps-overview.html",
                      "lastWriteIso":  "2026-03-10T13:42:14.9084291+00:00",
                      "sizeBytes":  7580,
                      "sizeLabel":  "7.4 KB"
                  },
                  {
                      "name":  "CRYO_AF_REVIEW_VNEXT.html",
                      "category":  "Scratch",
                      "group":  "Finrenone Experiments",
                      "kind":  "Scratch",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\vnext\\CRYO_AF_REVIEW_VNEXT.html",
                      "copyPath":  "C:\\Living metas\\Library\\Scratch\\Finrenone Experiments\\vnext -- CRYO_AF_REVIEW_VNEXT.html",
                      "copyName":  "vnext -- CRYO_AF_REVIEW_VNEXT.html",
                      "lastWriteIso":  "2026-03-07T15:24:27.4271498+00:00",
                      "sizeBytes":  122051,
                      "sizeLabel":  "119.2 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW_VNEXT.html",
                      "category":  "Scratch",
                      "group":  "Finrenone Experiments",
                      "kind":  "Scratch",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\vnext\\FINERENONE_REVIEW_VNEXT.html",
                      "copyPath":  "C:\\Living metas\\Library\\Scratch\\Finrenone Experiments\\vnext -- FINERENONE_REVIEW_VNEXT.html",
                      "copyName":  "vnext -- FINERENONE_REVIEW_VNEXT.html",
                      "lastWriteIso":  "2026-03-07T15:24:28.1650998+00:00",
                      "sizeBytes":  121652,
                      "sizeLabel":  "118.8 KB"
                  },
                  {
                      "name":  "teer (3).html",
                      "category":  "Scratch",
                      "group":  "TEER Scratch",
                      "kind":  "Scratch",
                      "sourceRoot":  "C:\\Projects\\HTML-Misc",
                      "originalPath":  "C:\\Projects\\HTML-Misc\\teer (3).html",
                      "copyPath":  "C:\\Living metas\\Library\\Scratch\\TEER Scratch\\teer (3).html",
                      "copyName":  "teer (3).html",
                      "lastWriteIso":  "2025-11-28T21:06:06.5812230+00:00",
                      "sizeBytes":  46561,
                      "sizeLabel":  "45.5 KB"
                  },
                  {
                      "name":  "teer.html",
                      "category":  "Scratch",
                      "group":  "TEER Scratch",
                      "kind":  "Scratch",
                      "sourceRoot":  "C:\\Projects\\HTML-Misc",
                      "originalPath":  "C:\\Projects\\HTML-Misc\\teer.html",
                      "copyPath":  "C:\\Living metas\\Library\\Scratch\\TEER Scratch\\teer.html",
                      "copyName":  "teer.html",
                      "lastWriteIso":  "2025-11-28T13:08:13.0777888+00:00",
                      "sizeBytes":  46561,
                      "sizeLabel":  "45.5 KB"
                  },
                  {
                      "name":  "ABLATION_AF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\ABLATION_AF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- ABLATION_AF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- ABLATION_AF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.2161842+00:00",
                      "sizeBytes":  999778,
                      "sizeLabel":  "976.3 KB"
                  },
                  {
                      "name":  "ARNI_HF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\ARNI_HF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- ARNI_HF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- ARNI_HF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.2507618+00:00",
                      "sizeBytes":  999557,
                      "sizeLabel":  "976.1 KB"
                  },
                  {
                      "name":  "ATTR_CM_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\ATTR_CM_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- ATTR_CM_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- ATTR_CM_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.2805297+00:00",
                      "sizeBytes":  1001267,
                      "sizeLabel":  "977.8 KB"
                  },
                  {
                      "name":  "ATTR_CM_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\ATTR_CM_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- ATTR_CM_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- ATTR_CM_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-14T22:06:50.7115452+00:00",
                      "sizeBytes":  27495,
                      "sizeLabel":  "26.9 KB"
                  },
                  {
                      "name":  "AutoGRADE.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\AutoGRADE.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- AutoGRADE.html",
                      "copyName":  "e156-submission -- assets -- AutoGRADE.html",
                      "lastWriteIso":  "2026-03-15T14:37:19.8969631+00:00",
                      "sizeBytes":  38750,
                      "sizeLabel":  "37.8 KB"
                  },
                  {
                      "name":  "AutoManuscript.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\AutoManuscript.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- AutoManuscript.html",
                      "copyName":  "e156-submission -- assets -- AutoManuscript.html",
                      "lastWriteIso":  "2026-03-18T07:00:58.5139278+00:00",
                      "sizeBytes":  44739,
                      "sizeLabel":  "43.7 KB"
                  },
                  {
                      "name":  "BEMPEDOIC_ACID_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\BEMPEDOIC_ACID_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- BEMPEDOIC_ACID_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- BEMPEDOIC_ACID_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.3237766+00:00",
                      "sizeBytes":  1011759,
                      "sizeLabel":  "988.0 KB"
                  },
                  {
                      "name":  "COLCHICINE_CVD_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\COLCHICINE_CVD_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- COLCHICINE_CVD_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- COLCHICINE_CVD_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:48:49.7183824+00:00",
                      "sizeBytes":  825632,
                      "sizeLabel":  "806.3 KB"
                  },
                  {
                      "name":  "COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- COLCHICINE_CVD_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-18T07:13:17.1956855+00:00",
                      "sizeBytes":  816955,
                      "sizeLabel":  "797.8 KB"
                  },
                  {
                      "name":  "DOAC_CANCER_VTE_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\DOAC_CANCER_VTE_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- DOAC_CANCER_VTE_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- DOAC_CANCER_VTE_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.3799484+00:00",
                      "sizeBytes":  998665,
                      "sizeLabel":  "975.3 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\FINERENONE_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- FINERENONE_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- FINERENONE_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.4246239+00:00",
                      "sizeBytes":  1015944,
                      "sizeLabel":  "992.1 KB"
                  },
                  {
                      "name":  "FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "copyName":  "e156-submission -- assets -- FINERENONE_REVIEW.pre_hr_rr_backup.html",
                      "lastWriteIso":  "2026-03-10T14:58:10.1886641+00:00",
                      "sizeBytes":  659847,
                      "sizeLabel":  "644.4 KB"
                  },
                  {
                      "name":  "GLP1_CVOT_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\GLP1_CVOT_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- GLP1_CVOT_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- GLP1_CVOT_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:48:50.1624039+00:00",
                      "sizeBytes":  1115492,
                      "sizeLabel":  "1,089.3 KB"
                  },
                  {
                      "name":  "GLP1_CVOT_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- GLP1_CVOT_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- GLP1_CVOT_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-18T07:13:30.5501045+00:00",
                      "sizeBytes":  1106815,
                      "sizeLabel":  "1,080.9 KB"
                  },
                  {
                      "name":  "INCRETIN_HFpEF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\INCRETIN_HFpEF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.4773071+00:00",
                      "sizeBytes":  1001919,
                      "sizeLabel":  "978.4 KB"
                  },
                  {
                      "name":  "INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- INCRETIN_HFpEF_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-14T22:17:10.0153410+00:00",
                      "sizeBytes":  430644,
                      "sizeLabel":  "420.6 KB"
                  },
                  {
                      "name":  "INTENSIVE_BP_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\INTENSIVE_BP_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- INTENSIVE_BP_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- INTENSIVE_BP_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:54:28.0977983+00:00",
                      "sizeBytes":  997648,
                      "sizeLabel":  "974.3 KB"
                  },
                  {
                      "name":  "IV_IRON_HF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\IV_IRON_HF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- IV_IRON_HF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- IV_IRON_HF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.5456056+00:00",
                      "sizeBytes":  999008,
                      "sizeLabel":  "975.6 KB"
                  },
                  {
                      "name":  "LIPID_HUB_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\LIPID_HUB_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- LIPID_HUB_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- LIPID_HUB_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:54:28.1285090+00:00",
                      "sizeBytes":  1004442,
                      "sizeLabel":  "980.9 KB"
                  },
                  {
                      "name":  "LivingMeta.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\LivingMeta.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- LivingMeta.html",
                      "copyName":  "e156-submission -- assets -- LivingMeta.html",
                      "lastWriteIso":  "2026-03-18T12:16:38.6564042+00:00",
                      "sizeBytes":  962645,
                      "sizeLabel":  "940.1 KB"
                  },
                  {
                      "name":  "MAVACAMTEN_HCM_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\MAVACAMTEN_HCM_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- MAVACAMTEN_HCM_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- MAVACAMTEN_HCM_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.6229998+00:00",
                      "sizeBytes":  998473,
                      "sizeLabel":  "975.1 KB"
                  },
                  {
                      "name":  "META_DASHBOARD.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\META_DASHBOARD.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- META_DASHBOARD.html",
                      "copyName":  "e156-submission -- assets -- META_DASHBOARD.html",
                      "lastWriteIso":  "2026-03-18T06:59:40.9208409+00:00",
                      "sizeBytes":  69180,
                      "sizeLabel":  "67.6 KB"
                  },
                  {
                      "name":  "MetaExtract.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\MetaExtract.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- MetaExtract.html",
                      "copyName":  "e156-submission -- assets -- MetaExtract.html",
                      "lastWriteIso":  "2026-03-15T14:37:19.9652727+00:00",
                      "sizeBytes":  15760,
                      "sizeLabel":  "15.4 KB"
                  },
                  {
                      "name":  "PCSK9_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\PCSK9_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- PCSK9_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- PCSK9_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.6623159+00:00",
                      "sizeBytes":  1004457,
                      "sizeLabel":  "980.9 KB"
                  },
                  {
                      "name":  "RENAL_DENERV_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\RENAL_DENERV_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- RENAL_DENERV_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- RENAL_DENERV_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.6915915+00:00",
                      "sizeBytes":  1001002,
                      "sizeLabel":  "977.5 KB"
                  },
                  {
                      "name":  "RIVAROXABAN_VASC_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\RIVAROXABAN_VASC_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- RIVAROXABAN_VASC_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- RIVAROXABAN_VASC_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.7254603+00:00",
                      "sizeBytes":  999637,
                      "sizeLabel":  "976.2 KB"
                  },
                  {
                      "name":  "SGLT2_CKD_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\SGLT2_CKD_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- SGLT2_CKD_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- SGLT2_CKD_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:53:35.7706129+00:00",
                      "sizeBytes":  998888,
                      "sizeLabel":  "975.5 KB"
                  },
                  {
                      "name":  "SGLT2_HF_REVIEW.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\SGLT2_HF_REVIEW.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- SGLT2_HF_REVIEW.html",
                      "copyName":  "e156-submission -- assets -- SGLT2_HF_REVIEW.html",
                      "lastWriteIso":  "2026-03-19T19:48:51.6964910+00:00",
                      "sizeBytes":  838741,
                      "sizeLabel":  "819.1 KB"
                  },
                  {
                      "name":  "SGLT2_HF_REVIEW.v11.bak.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\SGLT2_HF_REVIEW.v11.bak.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- SGLT2_HF_REVIEW.v11.bak.html",
                      "copyName":  "e156-submission -- assets -- SGLT2_HF_REVIEW.v11.bak.html",
                      "lastWriteIso":  "2026-03-18T07:13:46.2169187+00:00",
                      "sizeBytes":  830064,
                      "sizeLabel":  "810.6 KB"
                  },
                  {
                      "name":  "TrialRadar.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\assets\\TrialRadar.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- assets -- TrialRadar.html",
                      "copyName":  "e156-submission -- assets -- TrialRadar.html",
                      "lastWriteIso":  "2026-03-15T14:37:19.9303603+00:00",
                      "sizeBytes":  20302,
                      "sizeLabel":  "19.8 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Submission",
                      "group":  "Finrenone E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\Finrenone",
                      "originalPath":  "C:\\Projects\\Finrenone\\e156-submission\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Finrenone E156 Submission\\e156-submission -- index.html",
                      "copyName":  "e156-submission -- index.html",
                      "lastWriteIso":  "2026-03-28T11:38:46.8517972+00:00",
                      "sizeBytes":  24042,
                      "sizeLabel":  "23.5 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\e156-submission\\assets\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Living Meta App E156 Submission\\e156-submission -- assets -- index.html",
                      "copyName":  "e156-submission -- assets -- index.html",
                      "lastWriteIso":  "2026-01-02T01:28:57.3523350+00:00",
                      "sizeBytes":  3685,
                      "sizeLabel":  "3.6 KB"
                  },
                  {
                      "name":  "living-meta-complete.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\e156-submission\\assets\\living-meta-complete.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Living Meta App E156 Submission\\e156-submission -- assets -- living-meta-complete.html",
                      "copyName":  "e156-submission -- assets -- living-meta-complete.html",
                      "lastWriteIso":  "2026-01-19T22:41:12.4452813+00:00",
                      "sizeBytes":  120450,
                      "sizeLabel":  "117.6 KB"
                  },
                  {
                      "name":  "living-meta-standalone.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\e156-submission\\assets\\living-meta-standalone.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Living Meta App E156 Submission\\e156-submission -- assets -- living-meta-standalone.html",
                      "copyName":  "e156-submission -- assets -- living-meta-standalone.html",
                      "lastWriteIso":  "2026-03-28T10:54:14.3608644+00:00",
                      "sizeBytes":  30693,
                      "sizeLabel":  "30.0 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Submission",
                      "group":  "Living Meta App E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\HTML apps\\living-meta",
                      "originalPath":  "C:\\HTML apps\\living-meta\\e156-submission\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Living Meta App E156 Submission\\e156-submission -- index.html",
                      "copyName":  "e156-submission -- index.html",
                      "lastWriteIso":  "2026-03-28T11:38:44.5669498+00:00",
                      "sizeBytes":  22926,
                      "sizeLabel":  "22.4 KB"
                  },
                  {
                      "name":  "living-meta-engine.html",
                      "category":  "Submission",
                      "group":  "Living Meta Engine E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\living-meta-engine",
                      "originalPath":  "C:\\Projects\\living-meta-engine\\e156-submission\\assets\\living-meta-engine.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Living Meta Engine E156 Submission\\e156-submission -- assets -- living-meta-engine.html",
                      "copyName":  "e156-submission -- assets -- living-meta-engine.html",
                      "lastWriteIso":  "2026-03-25T16:24:18.5823525+00:00",
                      "sizeBytes":  44797,
                      "sizeLabel":  "43.7 KB"
                  },
                  {
                      "name":  "index.html",
                      "category":  "Submission",
                      "group":  "Living Meta Engine E156 Submission",
                      "kind":  "Submission",
                      "sourceRoot":  "C:\\Projects\\living-meta-engine",
                      "originalPath":  "C:\\Projects\\living-meta-engine\\e156-submission\\index.html",
                      "copyPath":  "C:\\Living metas\\Library\\Submission\\Living Meta Engine E156 Submission\\e156-submission -- index.html",
                      "copyName":  "e156-submission -- index.html",
                      "lastWriteIso":  "2026-03-28T11:38:47.0046389+00:00",
                      "sizeBytes":  22039,
                      "sizeLabel":  "21.5 KB"
                  }
              ]
};
